apiVersion: v1
kind: Plugin
metadata:
  author: langbot
  name: NahidaNewDemo
  repository: 'https://github.com/langbot-app/NahidaNewDemo'
  version: 0.1.0
  description:
    en_US: Plugin for sending images of Nahida
    zh_CN: Nahida的图片发送插件
  label:
    en_US: Nahida New
    zh_CN: Nahida New
spec:
  config:
    - name: github_token
      label:
        en_US: Github Token
        zh_CN: Github Token
      description:
        en_US: Image downloading requires a Github token
        zh_CN: 如果不填的话，图片可能会下载失败
      default: ''
      required: false
execution:
  python:
    path: main.py
    attr: NahidaPlugin
